export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  CONNECTIONS_REPOSITOTY: "CONNECTIONS_REPOSITOTY",
  STATUS_REPOSITORY: "STATUS_REPOSITORY",
  BLOB_REPOSIRORY: "BLOB_REPOSITORY",
  CDN_STORAGE: "blobCache",
};