export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  ROLES_REPOSITORY: "ROLES_REPOSITORY",
  USER_ROLES_REPOSITORY: "USER_ROLES_REPOSITORY",
  BLOB_REPOSIRORY: "BLOB_REPOSITORY",
  CDN_STORAGE: "blobCache",
};